# Generated by Django 5.1.6 on 2025-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_lecturehall_projector_lecturehall_ac_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturehall',
            name='non_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
