# Generated by Django 5.1.6 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_is_approved_remove_booking_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_token',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
