# Generated by Django 5.1.6 on 2025-03-20 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_approval_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
