# Generated by Django 5.1.6 on 2025-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
