# Generated by Django 5.1.6 on 2025-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ac_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='projector_required',
            field=models.BooleanField(default=False),
        ),
    ]
