# Generated by Django 5.1.6 on 2025-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_booking_time_slot_booking_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('non-academic', 'Non-Academic')], default='non-academic', max_length=20),
        ),
    ]
