# Generated by Django 5.1.6 on 2025-03-25 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decision_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
