# Generated by Django 5.1.6 on 2025-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_decision_time_booking_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_tokens',
            field=models.JSONField(default=dict),
        ),
    ]
